#include <format.h>

FormatInfo getFormatInfo(const Format format) {
    static const FormatInfo formatInfos[Format_Count] = {
        {"UNKNOWN"          ,  0},
        {"R8_UINT"          ,  1},
        {"R8_SINT"          ,  1},
        {"R8_UNORM"         ,  1},
        {"R8_SNORM"         ,  1},
        {"RG8_UINT"         ,  2},
        {"RG8_SINT"         ,  2},
        {"RG8_UNORM"        ,  2},
        {"RG8_SNORM"        ,  2},
        {"R16_UINT"         ,  2},
        {"R16_SINT"         ,  2},
        {"R16_UNORM"        ,  2},
        {"R16_SNORM"        ,  2},
        {"R16_FLOAT"        ,  2},
        {"BGRA4_UNORM"      ,  2},
        {"B5G6R5_UNORM"     ,  2},
        {"B5G5R5A1_UNORM"   ,  2},
        {"RGBA8_UINT"       ,  4},
        {"RGBA8_SINT"       ,  4},
        {"RGBA8_UNORM"      ,  4},
        {"RGBA8_SNORM"      ,  4},
        {"BGRA8_UNORM"      ,  4},
        {"SRGBA8_UNORM"     ,  4},
        {"SBGRA8_UNORM"     ,  4},
        {"R10G10B10A2_UNORM",  4},
        {"R11G11B10_FLOAT"  ,  4},
        {"RG16_UINT"        ,  4},
        {"RG16_SINT"        ,  4},
        {"RG16_UNORM"       ,  4},
        {"RG16_SNORM"       ,  4},
        {"RG16_FLOAT"       ,  4},
        {"R32_UINT"         ,  4},
        {"R32_SINT"         ,  4},
        {"R32_FLOAT"        ,  4},
        {"RGBA16_UINT"      ,  8},
        {"RGBA16_SINT"      ,  8},
        {"RGBA16_FLOAT"     ,  8},
        {"RGBA16_UNORM"     ,  8},
        {"RGBA16_SNORM"     ,  8},
        {"RG32_UINT"        ,  8},
        {"RG32_SINT"        ,  8},
        {"RG32_FLOAT"       ,  8},
        {"RGB32_UINT"       , 12},
        {"RGB32_SINT"       , 12},
        {"RGB32_FLOAT"      , 12},
        {"RGBA32_UINT"      , 16},
        {"RGBA32_SINT"      , 16},
        {"RGBA32_FLOAT"     , 16},
        {"D16"              ,  2},
        {"D24S8"            ,  4},
        {"X24G8_UINT"       ,  4},
        {"D32"              ,  4},
        {"D32S8"            ,  8},
        {"X32G8_UINT"       ,  8},
        {"BC1_UNORM"        ,  8},
        {"BC1_UNORM_SRGB"   ,  8},
        {"BC2_UNORM"        , 16},
        {"BC2_UNORM_SRGB"   , 16},
        {"BC3_UNORM"        , 16},
        {"BC3_UNORM_SRGB"   , 16},
        {"BC4_UNORM"        ,  8},
        {"BC4_SNORM"        ,  8},
        {"BC5_UNORM"        , 16},
        {"BC5_SNORM"        , 16},
        {"BC6H_UFLOAT"      , 16},
        {"BC6H_SFLOAT"      , 16},
        {"BC7_UNORM"        , 16},
        {"BC7_UNORM_SRGB"   , 16},
    };

    return format < Format_Count ? formatInfos[format] : formatInfos[0];
}
